config/routes.rb
Rails.application.routes.draw do

  # Devise routes for admin_users and users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # Resources for other models
  resources :groups
  resources :members
  resources :groupchats
  resources :messages
  resources :profiles
  resources :friend_requests
  resources :friendships

  # Nested resources for posts, comments, and likes
  resources :posts do
    resources :comments
    resources :likes
  end

  # resources :groups do
  #   resources :members
  # end

  # Custom routes
  get 'friends/index'
  get 'friends/destroy'
  get "/update_user" , to: "friend_requests#update_user"

  # Root route
  root to: "homes#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  def self.ransackable_attributes(auth_object = nil)
    ["comment_text", "created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  belongs_to :user
  belongs_to :friend, class_name: 'User'


  def accept
    user.friends << friend
    friend.friends << user
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  after_create :create_inverse_relationship

  belongs_to :user
  belongs_to :friend,class_name: "User", foreign_key: :friend_id


  private
  def create_inverse_relationship
    # @friend_ship = friend.friendships.new(friend: user)
    # @friend_ship.save
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :members
  has_many :users, through: :members
  has_many :groupchats

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_name", "id", "updated_at", "user_id"]
  end
end

app/models/groupchat.rb
class Groupchat < ApplicationRecord
    belongs_to :member, class_name:"User", foreign_key: "sender_id"
    belongs_to :group
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_id", "id", "updated_at", "user_id"]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "receiver_id", "sender_id", "text", "updated_at"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 3
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "user_id"]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_pic, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["about", "address", "bio", "created_at", "dob", "id", "updated_at", "user_id", "username"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["profile_pic_attachment", "profile_pic_blob", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    ["comments", "friend_requests", "friends", "friendships", "group_owners", "groups", "likes", "members", "messaged", "messagee", "pending_friends", "posts", "profile", "receivers", "senders"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes
  has_one :profile

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'
  has_many :senders, through: :messagee
  has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
  has_many :receivers, through: :messaged

  has_many :group_owners, class_name: "Group", foreign_key: :user_id

  has_many :members
  has_many :groups, through: :members
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :get_profile, only: [:index, :edit, :update]

  def index
    @posts = current_user.posts.order(:title).page params[:page]
    # ids = current_user.friend_requests.pluck(:friend_id)
    ids = current_user.friendships.pluck(:friend_id)
    @users = User.where.not(id: [ids])
    @incoming = FriendRequest.where(friend: current_user)
    @outgoing = current_user.friend_requests
    @friend_ship = current_user.friendships.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    if @profile.save
      redirect_to profiles_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profiles_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def get_profile 
      @profile = current_user.profile
    end
    
    def profile_params
      params.require(:profile).permit(:username, :address, :dob, :about, :bio, :user_id, :image)
    end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with model: profile do |form| %>

    <div>
      <%= form.label :username %>
      <%= form.text_field :username %> <br> <br> 
    </div>

    <div>
      <%= form.label :address %>
      <%= form.text_field :address %> <br> <br> 
    </div>

    <div>
      <%= form.label :dob %>
      <%= form.date_field :dob %> <br> <br> 
    </div>

    <div>
      <%= form.label :about %>
      <%= form.text_area :about %> <br> <br> 
    </div>

    <div>
      <%= form.label :bio %>
      <%= form.text_area :bio %> <br> <br> 
    </div>

    <div>
      <%= form.label :image %>
      <%= form.file_field :image %> <br> <br> 
    </div>

    <div>
      <%= form.hidden_field :user_id %>
    </div>
    
    <div>
      <%= form.submit %>
    </div>
<% end %>

<%#= link_to "Back Profile", profile_path %>
  

app/views/profiles/edit.html.erb
<div style='padding:100px; margin-left:180px'>
    <%= render "form", profile: @profile %>
</div>

app/views/profiles/index.html.erb
<h1 style='margin-left:450px'>Profile</h1>
<div style='padding:80px'>
    <% if @profile.nil? %>
        <%= link_to "Add Profile Detail", new_profile_path %>
    <% else %>
        <div class="position-absolute top-50 start-50 translate-middle" >
            <% if current_user.profile.profile_pic.attached? %>
                <%= image_tag current_user.profile.profile_pic %>
            <% end %>
        </div>

        <p>Total Post :- <%= current_user.posts.ids.count %> </p>
        <p> Email :- <%= current_user.email %> </p>
        <p> Current User :- <%= current_user.id %> </p>
        <p> Profile ID :- <%= @profile&.id %> </p>
        <p> Username :- <%= @profile&.username %> </p>
        <p> User ID :- <%= @profile&.user_id %> </p>
        <p> Address :- <%= @profile&.address %> </p>
        <p> Bio :- <%= @profile&.bio %> </p>
        <p> About :- <%= @profile&.about %> </p>
        <p> Date of Birth :- <%= @profile&.dob %> </p>
        <%= link_to "Edit profile", edit_profile_path(current_user) %>
    <% end %>

    <br>

    <div class="btn btn-outline-warning" style="margin-top:50px">
        <%= link_to 'Messanger', messages_path %> 
    </div> <br>
    <div class="btn btn-outline-warning" style="margin-top:50px">
        <%= link_to 'Group Messanger', groups_path %> 
    </div>

</div>

<% if current_user.posts.count == 0 %>
    <div class="position-absolute bottom-0 start-50 translate-middle-x" >
        <p> Add Post </p> 
        <div class="btn btn-outline-primary" >
            <%= link_to "Create New post", new_post_path %>
        </div>
    </div>
<% else %>
    <div style="margin-left:80px">
        <h3> Post </h3>
        <ol>
            <% @posts&.each do |post| %>
                <li> Title :- <%= link_to post.title, post %> </li>
            <% end %>
        </ol>
    </div>
<% end %>


<div style='margin-left:80px'>
    <h1 style="color:blue"  > Recommendation </h1>
    <%# byebug %>
    <% @users.each do |user| %>
        <% if current_user.id == user.id %>
            <% next %>
        <% else %>
            <%= user.email %>
            <%= button_to "Follow", friend_requests_path(id: user.id) %>
        <% end %>
    <% end %>
</div>
        
<br>

<% a = 0 %>
<% @incoming.each do |i| %>
    <p> Incoming Request :- <% a+=1 %> <%= a %>
        <b>User ID :- </b> <%= i.user_id %>
        <b>User Email :- </b> <%= i.user.email %>
        <%= link_to "Accept Request", update_user_path(id: i.id) %>   
    </p>
<% end %>


<% a = 0 %>
<% @outgoing.each do |i| %>
    <p> Outgoing Request :- <% a+=1 %> <%= a %> 
        <b>User ID :- </b> <%= i.friend_id %> 
        <b>User Email :- </b> <%= i.friend.email %>
        <b> | Request Pending... </b>
    </p>
<% end %>

<br>
<br>
<h1>Friend List </h1>
<% a = 0 %>
<% @friend_ship.each do |i| %>
    <%= a += 1 %>. <%= i.friend.email %>
    <%= link_to "Unfollow", friends_destroy_path(id: i.id), method: :delete %>
    <br>
<% end %>

app/views/profiles/new.html.erb
<div style='padding:100px; margin-left:180px'>
    <%= render "form", profile: @profile %>
</div>

app/views/profiles/show.html.erb
<p> <b> Username :- </b> <%= @profile.username %> <p>
<p> <b> Address :- </b> <%= @profile.address %> <p>
<p> <b> Bio :- </b> <%= @profile.bio %> <p>
<p> <b> About :- </b> <%= @profile.about %> <p>
<p> <b> Date of Birth :- </b> <%= @profile.dob %> <p>
<p> <b> User ID :- </b> <%= @profile.user_id %> <p>

<%= link_to "Edit profile", edit_profile_path(@profile) %> | 
<%= link_to "Back Profile", profiles_path %>