config/routes.rb
Rails.application.routes.draw do

  # Devise routes for admin_users and users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # Resources for other models
  resources :groups
  resources :members
  resources :groupchats
  resources :messages
  resources :profiles
  resources :friend_requests
  resources :friendships

  # Nested resources for posts, comments, and likes
  resources :posts do
    resources :comments
    resources :likes
  end

  # resources :groups do
  #   resources :members
  # end

  # Custom routes
  get 'friends/index'
  get 'friends/destroy'
  get "/update_user" , to: "friend_requests#update_user"

  # Root route
  root to: "homes#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  def self.ransackable_attributes(auth_object = nil)
    ["comment_text", "created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  belongs_to :user
  belongs_to :friend, class_name: 'User'


  def accept
    user.friends << friend
    friend.friends << user
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  after_create :create_inverse_relationship

  belongs_to :user
  belongs_to :friend,class_name: "User", foreign_key: :friend_id


  private
  def create_inverse_relationship
    # @friend_ship = friend.friendships.new(friend: user)
    # @friend_ship.save
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :members
  has_many :users, through: :members
  has_many :groupchats

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_name", "id", "updated_at", "user_id"]
  end
end

app/models/groupchat.rb
class Groupchat < ApplicationRecord
    belongs_to :member, class_name:"User", foreign_key: "sender_id"
    belongs_to :group
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_id", "id", "updated_at", "user_id"]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "receiver_id", "sender_id", "text", "updated_at"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 3
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "user_id"]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_pic, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["about", "address", "bio", "created_at", "dob", "id", "updated_at", "user_id", "username"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["profile_pic_attachment", "profile_pic_blob", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    ["comments", "friend_requests", "friends", "friendships", "group_owners", "groups", "likes", "members", "messaged", "messagee", "pending_friends", "posts", "profile", "receivers", "senders"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes
  has_one :profile

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'
  has_many :senders, through: :messagee
  has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
  has_many :receivers, through: :messaged

  has_many :group_owners, class_name: "Group", foreign_key: :user_id

  has_many :members
  has_many :groups, through: :members
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def index
        # byebug
        @groups = current_user.group_owners
        @sender = current_user
        @group_list = current_user.groups
    end
    def show
        # byebug
        @sender = current_user
        @group = Group.find(params[:id])
        @members = @group.users
        @groupchat = @group.groupchats
        @group_not_your = @group.members
        @group_admin = @group.user
    end

    def new 
        @group = Group.new
    end

    def edit
        @group = Group.find(params[:id])
    end

    def create
        # byebug
        @group = Group.new(group_params)
        @group.user_id = current_user.id 
        if @group.save
            redirect_to groups_path
        else
            render :new, status: :unprocessable_entity 
        end
    end
 
    def update
        @group = Group.find(params[:id])
        if @group.update(group_params)
            redirect_to groups_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @group = Group.find(params[:id])
        @group.destroy
    
        redirect_to groups_path, status: :see_other
    end

    private
    def group_params
        params.require(:group).permit(:group_name, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/edit.html.erb
<div style="padding:70px" >
    <h1>Enter Group Name </h1>
    <%= form_with model: @group do |form| %>
        <div>
            <%= form.label :group_name %>
            <%= form.text_field :group_name %> <br> <br>
            <% @group.errors.full_messages_for(:group_name).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    
        <div>
            <%= form.hidden_field :user_id %> <br> <br>
        </div>
    
        <div>
            <%= form.submit %>
        </div>
    
    <% end %>
</div>

app/views/groups/index.html.erb
<div style="padding:70px">
    <h1> Group Message Box </h1> <b>Current User Email :- <%= current_user.email %> </b>

    <br><br>
    <%= link_to "Create a Group", new_group_path %>
    <br><br>
    <h2>It's Your Group </h2>
    <% @groups.each do |i| %>
        <p>
            <b> Group Name :- </b> <%= i.group_name %>
            <b> User ID :- </b> <%= i.user_id %> <br> |
            <%= link_to "View Group", group_path(i) %> | 
            <%= link_to "Edit Group", edit_group_path(id: i.id) %> | 
            <%= link_to "Delete Group", group_path(id: i.id), data: {
                turbo_method: :delete, turbo_confirm: "Are You Sure Delete #{i.group_name} ?" } %> |
            <%= link_to "Add Members", members_path(id: i.id) %> | 

            <%#= button_to "Delete Group", group_path(id: i.id), method: :delete %>
        </p>
    <% end %> <br> <br>

    <h2> Not Your Group </h2>
    <% @group_list.each do |i| %>
        <p>
            <b> Group Name :- </b> <%= i.group_name %>
            <b> User ID :- </b> <%= i.user_id %> <br> |
            <%= link_to "View Group", group_path(i) %> | 
            <%= link_to "Edit Group", edit_group_path(id: i.id) %> | 
            <%= link_to "Delete Group", group_path(id: i.id), data: {
                turbo_method: :delete, turbo_confirm: "Are You Sure Delete #{i.group_name} ?" } %> |
            <%= link_to "Add Members", members_path(id: i.id) %> | 

            <%#= button_to "Delete Group", group_path(id: i.id), method: :delete %>
        </p>
    <% end %>
</div>

app/views/groups/new.html.erb
<div style="padding:70px" >
    <h1>Enter Group Name </h1>
    <%= form_with model: @group do |form| %>
        <div>
            <%= form.label :group_name %>
            <%= form.text_field :group_name %> <br> <br>
            <% @group.errors.full_messages_for(:group_name).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    
        <div>
            <%= form.hidden_field :user_id %> <br> <br>
        </div>
    
        <div>
            <%= form.submit %>
        </div>
    
    <% end %>
</div>

app/views/groups/show.html.erb
<div style="padding:70px">
    <h3> Group Name :- <%= @group.group_name %> </h3>
    <h5 style="margin-left:100px"> Group Admin :- <%= @group_admin.email %> </h5>
    <h6> <%= link_to "Back To Page", groups_path %> </h6>

    <% @members.each do |i| %>
        <%= i.id %>.
        <%= i.email %> <br>
    <% end %> <br>
    
    <h3> Messages :- <%= current_user.email %> </h3>

    <% @groupchat.each do |i| %>
        <b> <%= i.member.email %> :- </b> <%= i.text %> <br>
    <% end %>
    <br>

    <p> <b> Add Your Message :- </b> </p>

    <div style="margin-left:70px">
        <%= form_tag groupchats_path  do %>
            <div>
                <%= text_field_tag :text, nil, placeholder: 'Type here...',class: 'form-control' %>
                <%= hidden_field_tag "group_id", @group.id %>
                <%= hidden_field_tag "sender_id", @sender.id %>
                <%= submit_tag "Send", data: { disable_with: false } %>
            </div>
        <% end %>
    </div>
</div>