config/routes.rb
Rails.application.routes.draw do

  # Devise routes for admin_users and users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  # ActiveAdmin routes
  ActiveAdmin.routes(self)

  # Resources for other models
  resources :groups
  resources :members
  resources :groupchats
  resources :messages
  resources :profiles
  resources :friend_requests
  resources :friendships

  # Nested resources for posts, comments, and likes
  resources :posts do
    resources :comments
    resources :likes
  end

  # resources :groups do
  #   resources :members
  # end

  # Custom routes
  get 'friends/index'
  get 'friends/destroy'
  get "/update_user" , to: "friend_requests#update_user"

  # Root route
  root to: "homes#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  def self.ransackable_attributes(auth_object = nil)
    ["comment_text", "created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  belongs_to :user
  belongs_to :friend, class_name: 'User'


  def accept
    user.friends << friend
    friend.friends << user
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # validates :friend_id, :user_id, uniqueness: true

  after_create :create_inverse_relationship

  belongs_to :user
  belongs_to :friend,class_name: "User", foreign_key: :friend_id


  private
  def create_inverse_relationship
    # @friend_ship = friend.friendships.new(friend: user)
    # @friend_ship.save
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "friend_id", "id", "updated_at", "user_id"]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :members
  has_many :users, through: :members
  has_many :groupchats

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_name", "id", "updated_at", "user_id"]
  end
end

app/models/groupchat.rb
class Groupchat < ApplicationRecord
    belongs_to :member, class_name:"User", foreign_key: "sender_id"
    belongs_to :group
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "group_id", "id", "updated_at", "user_id"]
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "receiver_id", "sender_id", "text", "updated_at"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 3
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "user_id"]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_pic, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["about", "address", "bio", "created_at", "dob", "id", "updated_at", "user_id", "username"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["profile_pic_attachment", "profile_pic_blob", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    ["comments", "friend_requests", "friends", "friendships", "group_owners", "groups", "likes", "members", "messaged", "messagee", "pending_friends", "posts", "profile", "receivers", "senders"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes
  has_one :profile

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'
  has_many :senders, through: :messagee
  has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
  has_many :receivers, through: :messaged

  has_many :group_owners, class_name: "Group", foreign_key: :user_id

  has_many :members
  has_many :groups, through: :members
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :check_user, only: %i[ update destroy edit]

  def index
    @posts = Post.order(:title).page params[:page]
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, status: :see_other
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :user_id) 
    end

    def check_user
      unless current_user.id == @post.user_id
        flash[:notice] = "Access denied"
        redirect_to posts_path
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %> <br> <br>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div> <% end %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, rows: 5, class: 'form-control' %> <br> <br>
    <% @post.errors.full_messages_for(:description).each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit "Create Post", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>


<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div style = 'margin-left:400px'>
  <div class="btn btn-outline-info" style='margin-left:-350px'>
    <%= link_to "Add New post", new_post_path %>
  </div>

  <div class="card" style="width: 380px;">
    <div class="card-body">
      <div id="posts">
        <% @posts.each do |post| %>
          <%= render post %>
            <h6>Post ID :- <%= post.id %> </h6>
            <h6>Title :- <%= post.title %> </h6>
            <h6>Description :- <%= post.description %> </h6>
            <h6>User Id :- <%= post.user_id %> </h5>
            <p>Like :- <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
            <p>
              <button class="btn btn-outline-info" style = 'margin-left:285px'>
                <%= link_to "View", post %>
              </button>
            </p> <hr>
        <% end %>
      </div>
    </div>
  </div>

</div>
  <div style='margin-left:400px; margin-top:20px'>
    <%= paginate @posts, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center", nav_class: "d-inline-block" %>
  </div>

app/views/posts/new.html.erb
<div class="position-absolute top-50 start-50 translate-middle">

  <h1>New post</h1>
  <%= render "form", post: @post %>
  <br>

  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>

</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <h5>Post ID :- <%= @post.id %></h5>
  <h5>Title :- <%= @post.title %></h5>
  <p>Description :- <%= @post.description %> </p>
  <p>User ID :- <%= @post.user_id %></p>

  <br>

<%#= ------------------------------ Like & Unlike ------------------------------ %>
  <p>
    <%= @post.likes.count %>
    <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%>
  </p>
  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>
<%#= ------------------------------ End Like & Unlike ------------------------------ %>

<% if @post.user == current_user %>
<%# byebug %>

  <%= link_to "Edit this post", edit_post_path(@post) %> -|-|-
  <%= link_to "Back to posts", posts_path %> <br>
  <%= button_to "Destroy this post", @post, method: :delete %>

<% end %>
</div>





<hr>
<b>Comments</b> <br>
  <% @comments&.each do |comment|%>
    <p> Comment :- <%= comment.comment_text %> </p>
    <p> Comment ID :- <%= comment.id %> </p>
    <p> User ID :- <%= comment.user_id %> </p>
    <p> Post ID :- <%= comment.post_id %> </p>
  <% end %>
<hr>

<%#= ------------------------------ Comment ------------------------------ %>
<h2>Comments</h2>
  <%= form_with model: [ @post, @post.comments.build ] do |form| %>
    <p>
      <%= form.label :comment_text %><br>
      <%= form.text_field :comment_text %>
    </p>
    <p>
      <%= form.submit %>  
    </p>
  <% end %>
<%#= ------------------------------ End Comment ------------------------------ %>